vaadin/eslint-config-vaadin

- index.js
I think we should catch those missing spaces automatically:
http://eslint.org/docs/rules/space-infix-ops
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/eslint-config-vaadin/2)
> Enable space-infix-ops rule

- index.js
In order to implement https://github.com/vaadin/vaadin-grid/issues/566 we need to allow `console.warn`. In future we will also need `console.error`.
`console.log` will still throw a linter error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/eslint-config-vaadin/5)
> Allow console.warn and console.error

- index.js
http://eslint.org/docs/rules/keyword-spacing
currently it's possible to submit if/for statements without spaces around keywords:
```js
if(foo) {
...
}else {
```
This rule will prevent such cases and force using spaces:
```js
if (foo) {
...
} else {
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/eslint-config-vaadin/8)
> Enable keyword-spacing rule

- index.js
http://eslint.org/docs/rules/curly
currently it's possible to submit if statement without curly brackets:
```js
if (foo)
bar;
```
This rule will prevent such cases. 
PS. ES6 arrow functions will be still okay, eslint won't complain about something like 
```js
Array.map((a, b) => a > b)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/eslint-config-vaadin/7)
> Enable curly rule to force curly brackets for if/for statements

- index.js
This rule is needed to prevent extra whitespaces in cases like this:
```js
if (variable ) {
//        ^
}
```
Noticed in https://github.com/vaadin/vaadin-upload/pull/218 by @web-padawan 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/eslint-config-vaadin/9)
> Enable space-in-parens rule

- index.js
Currently it's possible to occasionally submit trailing whitespaces.
Noticed in [vaadin/vaadin-text-field#366](https://github.com/vaadin/vaadin-text-field/pull/166#issuecomment-344532360) by @platosha
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/eslint-config-vaadin/10)
> Enable no-trailing-spaces rule

- index.js
- package.json
- [eslint-config-airbnb-base](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base/) - a popular config with a plenty of syntax rules, best practices etc.
- [@typescript-eslint/eslint-plugin](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin) - a config with recommended rules for TypeScript.
- [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import) - required by `airbnb-base`, configured to work with TypeScript.
- [eslint-plugin-lit](https://github.com/43081j/eslint-plugin-lit) - adding a bunch of [rules](https://github.com/43081j/eslint-plugin-lit#supported-rules) for linting lit-html  tagged literals
- [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) - enforces Prettier …
> Update to new configs & rules for LitElement

- package.json
It seems that we also need to export `./index.js` as `./index` to get rid of the following error:
```
Error: Cannot read config file: /Users/serhii/vaadin/start/node_modules/eslint-config-vaadin/typescript.js
Error: Cannot find module './index'
Require stack:
- /Users/serhii/vaadin/start/node_modules/eslint-config-vaadin/utils/resolve.js
```
> fix: export ./index.js as ./index

- README.md
> chore: use JS syntax in readme examples

- package.json
Added a missing `@babel/core` dependency to `package.json` to resolve the error when using `eslint-config-vaadin/javascript`:
```
Error: Failed to load parser '@babel/eslint-parser' declared in '.eslintrc.json » eslint-config-vaadin/javascript': Cannot find module '@babel/core/package.json'
```
> fix: add missing @babel/core dependency

- src/rules/testing.ts
- src/testing.ts
Just adding `chai-frinedly` to `plugins` isn't enough to make it work: we should also override the ESLint `no-unused-expressions` rule with the plugin's one.
> fix: add chai-friendly/no-unused-expression rule

- src/rules/testing.ts
At the moment, the `chai-friendly` rules conflict with `typescript-eslint/no-unused-expressions` when linting TypeScript files. All the `no-unused-expressions`-like rules should be disabled in `vaadin/testing` in favor of `chai-friendly/no-unused-expressions`.
> fix: disable typescript-eslint/no-unused-expressions in tests

- src/rules/typescript/extensions.ts
To avoid conflicts, the PR disables the JavaScript rules that are natively checked by the TypeScript compiler.
Inspired by [`typescript-eslint/eslint-recommended`](https://github.com/typescript-eslint/typescript-eslint/blob/99c091e0e3cf38a28aa5e1d1d2b03b602d51aa0a/packages/eslint-plugin/src/configs/eslint-recommended.ts#L11-L31).
> fix: disable the rules natively checked by the TS compiler

- src/rules/typescript/original.ts
The PR modifies `@typescript-eslint/member-ordering`'s configuration to let getters and setters be grouped by name rather than accessibility. Grouping by name is enforced by `grouped-accessor-pairs` and it conflicted with the previous configuration of `member-ordering`.
Fixes https://github.com/vaadin/eslint-config-vaadin/issues/33
> fix: group getters and setters by name rather than accessibility

- package.json
We missed to add the new config entrypoint to `"files"` so it doesn't work 😞 
- Bugfix
> fix: add typescript-requiring-type-checking to files

- README.md
- src/typescript-requiring-type-checking.ts
The PR makes the `typescript-requiring-type-checking` config extend from the `typescript` config instead of `javascript` in order to prevent the `javascript` rules from enabling on top of the `typescript` ones in the following case:
```json
{
"extends": [
"vaadin/typescript",
"vaadin/typescript-requiring-type-checking",
"vaadin/lit",
"vaadin/prettier"
]
}
```
> fix: prevent typescript rules from overriding with javascript ones

- src/rules/eslint/suggestions.ts
- src/rules/typescript/original.ts
In this PR, I suggest to change the following rules:
- `prefer-destructuring` — I remember that we have agreed that for renamed properties we won't enforce destructuring but for some reason the rule is still here.
- `@typescript-eslint/consistent-type-imports` — looks like since the latest revision, it get an additional option `fixStyle`. [[details]](https://typescript-eslint.io/rules/consistent-type-imports).
- `@typescript-eslint/member-ordering` — when I worked on this rule, I have introduced an unnecessary complexity while it should be way easier, especially considering that we're going to avoid using `public` and `private` members.
> refactor: improve several rules

- .gitignore
- package-lock.json
- package.json
- src/imports-typescript.ts
- src/rules/imports.ts
- src/typescript-requiring-type-checking.ts
- src/typescript.ts
- tools/missing-rule-checker/imports.mts
- tools/missing-rule-checker/index.mts
This PR introduces some improvements for `eslint-plugin-import` for TypeScript.
I have also updated a checking utility and a ruleset for this plugin.
> refactor: update import plugin & adapt it for Typescript

- .gitignore
- README.md
- package-lock.json
- package.json
- src/rules/eslint/suggestions.ts
- src/sort.ts
- tsconfig.json
This PR replaces the eslint [sort-keys](https://eslint.org/docs/latest/rules/sort-keys) rule with the optional config based on rules from [perfectionist](https://eslint-plugin-perfectionist.azat.io/) plugin.
The config enables the following rules from the plugin:
- [sort-enums](https://eslint-plugin-perfectionist.azat.io/rules/sort-enums),
- [sort-exports](https://eslint-plugin-perfectionist.azat.io/rules/sort-exports),
- [sort-jsx-props](https://eslint-plugin-perfectionist.azat.io/rules/sort-jsx-props),
- [sort-named-exports](https://eslint-plugin-perfectionist.azat.io/rules/sort-named-exports),
- [sort-objects](https://eslint-plugin-perfectionist.azat.io/rules/sort-objects)
Other rules are disabled either because they could break the code, they are already handled by other rules or they …
> feat: add sort config

- src/rules/typescript/original.ts
- src/sort.ts
Move `@typescript-eslint/member-ordering` to `sort` rule set; it was considered too opinionated.
> refactor: move member ordering to sort rule set

- src/rules/eslint/suggestions.ts
The PR enables the [`require-await` rule](https://eslint.org/docs/latest/rules/require-await). 
This rule was originally disabled to allow marking functions as async not only when they have an `await` but also when they return a `Promise`. However, since there wasn't any other rule that would enforce async for Promise-returning functions, maintaining consistency of the async keyword for functions was totally up to the developer and often resulted in oversights.
> feat: enable require-await rule

- src/rules/typescript-requiring-type-checking/original.ts
- src/rules/typescript/original.ts
Moves `@typescript-eslint/no-mixed-enums` from `vaadin/typescript` to `vaadin/typescript-requiring-type-checking`, as this rule requires type information to run.
> fix: move no-mixed-enums to config with type checking

- src/typescript.ts
The `vaadin/typescript` config is designed to not require type information, so there is no need to specify `parserOptions.project`. In fact, the presence of this property caused errors in projects that don't include all the linted files in their TS config:
```
0:0  error  Parsing error: ESLint was configured to run on `<tsconfigRootDir>/web-test-runner.config.js` using `parserOptions.project`: /users/vursen/dev/vaadin/web-components/tsconfig.json
However, that TSConfig does not include this file. Either:
- Change ESLint's list of included files to not include this file
- Change that TSConfig to include this file
- Create a new TSConfig that includes this file and include it in your parserOptions.project
See the typescript-eslint docs for more info: …
```
> fix: remove parserOptions.project from vaadin/typescript

- package-lock.json
- package.json
I found that we have two versions of `prettier` loading. This PR fixes it
> chore: dedupe prettier

- src/rules/eslint/suggestions.ts
Number parameter is deprecated in favor of object parameter
> chore: update "max-params" options

- src/rules/typescript/extensions.ts
According to a result of typescript-eslint/typescript-eslint#1856, the issue is fixed, so we can enable that rule again
> refactor(typescript): enable no-unused-vars rule

- src/rules/typescript/extensions.ts
The original rule is in the `possible-problems` file.
- Bugfix
> fix(typescript): use correct file for no-unused-vars

- package-lock.json
- package.json
- src/rules/typescript/original.ts
Upgraded `typescript-eslint` dependencies and replaced the removed `@typescript-eslint/ban-types` rule with new rules added in https://github.com/typescript-eslint/typescript-eslint/pull/9102 (see also https://typescript-eslint.io/rules/ban-types/).
- Dependency bump
> feat: update typescript-eslint to v8, replace ban-types rule

- package-lock.json
- package.json
Upgraded `eslint-plugin-perfectionist` to latest version which also uses `typescript-eslint` v8 internally.
This should be merged after #78 so that we remove old dependencies from the `package-lock.json`.
- Dependency update
> feat: upgrade eslint-plugin-perfectionist to v3
